name: audio_player_flutter
description: Apple Music / Tidal Style Audio Player for Flutter
version: 0.0.1+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^0.15.1
  built_collection: ^4.3.2
  built_value: ^7.1.0
  flutter_bloc: ^4.0.0
  http: ^0.12.1
  transparent_image: ^1.0.0
  uuid: ^2.0.4

dev_dependencies:
  build_runner: ^1.9.0
  build_web_compilers: ^2.10.0
  built_value_generator: ^7.1.0
  mockito: ^4.1.1
  pedantic: ^1.9.0
  test: ^1.14.3
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
